"""
Auto-Generated Property-Based Tests
Generated by: tests/integration/test_generator.py

Property-based tests using hypothesis to verify invariants across
random inputs. These tests help discover edge cases and ensure
robustness.

DO NOT EDIT MANUALLY - Regenerate using test_generator.py
"""

import pytest
import sys
from pathlib import Path
from hypothesis import given, strategies as st, settings, HealthCheck

# Add parent to path
sigmalang_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(sigmalang_root))

# Configure hypothesis for CI
settings.register_profile("ci", max_examples=50, deadline=5000)
settings.register_profile("dev", max_examples=10, deadline=2000)
settings.load_profile("dev")


class TestEncoderProperties:
    """Property-based tests for encoder service."""

    @pytest.mark.integration
    @pytest.mark.property
    @given(st.text(min_size=1, max_size=1000))
    def test_encode_decode_roundtrip(self, text):
        """Property: encode(text) -> decode(encoded) == original tree structure."""
        from sigmalang.core.api_server import create_api

        api = create_api()
        api.initialize()

        # Parse and encode
        from sigmalang.core.parser import SemanticParser
        parser = SemanticParser()
        tree = parser.parse(text)

        from sigmalang.core.encoder import SigmaEncoder
        encoder = SigmaEncoder()
        encoded = encoder.encode(tree)
        assert encoded is not None
        assert len(encoded) > 0

    @pytest.mark.integration
    @pytest.mark.property
    @given(st.text(min_size=1, max_size=100))
    def test_compression_always_produces_output(self, text):
        """Property: compression always produces non-empty output."""
        from sigmalang.core.api_server import create_api

        api = create_api()
        api.initialize()

        # This should never fail or return empty
        from sigmalang.core.parser import SemanticParser
        from sigmalang.core.encoder import SigmaEncoder

        parser = SemanticParser()
        encoder = SigmaEncoder()

        tree = parser.parse(text)
        encoded = encoder.encode(tree)

        assert encoded is not None
        assert len(encoded) > 0



class TestSearchProperties:
    """Property-based tests for search service."""

    @pytest.mark.integration
    @pytest.mark.property
    @given(st.text(min_size=1, max_size=100), st.integers(min_value=1, max_value=10))
    def test_search_top_k_returns_at_most_k(self, query, k):
        """Property: search with top_k=k returns at most k results."""
        from sigmalang.core.api_server import create_api

        api = create_api()
        api.initialize()

        # Build a small corpus
        corpus = ["test document", "another document", "third document"]

        try:
            results = api.search.semantic_search(query, corpus, top_k=k)
            assert len(results) <= k, f"Expected at most {k} results, got {len(results)}"
        except Exception:
            # Some queries might not work, that's ok for property testing
            pass
